<a href="https://colab.research.google.com/github/trenjoh/Data-Analysis-with-Python/blob/main/Analyzing_dt_from_DF(pandas).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

# ANALYZING DATA FROM DATAFRAMES

In [2]:
import pandas as pd

In [3]:
dt = pd.read_csv('/content/drive/My Drive/Colab Notebooks/weather_data_updated.csv',header=0)
print(dt)

        Town  Min_temp(°C)  Max_temp(°C) Temperature Category
0    Nairobi          14.0          22.0                 warm
1    Mombasa          22.0          29.0            very warm
2     Kisumu          20.0          26.0                 warm
3     Nakuru          14.0          20.0                 cold
4    Eldoret          16.0          23.0                 warm
5      Thika          15.0          21.0                 cold
6      Nyeri          16.0          25.0                 warm
7   Machakos          17.0          25.0                 warm
8       Meru          23.0          33.0            very warm
9       Embu          25.0          30.0            very warm
10   Kericho          27.0          33.0            very warm
11  Naivasha          16.0          28.0                 warm
12    Kitale          24.0          28.0                 warm
13   Malindi          25.0          34.0            very warm
14   Garissa          20.0          25.0                 warm
15  Kakamega          20.0          30.0            very warm
16   Nanyuki          25.0          32.0            very warm
17    Isiolo          16.0          21.0                 cold
18      Lamu          14.0          22.0                 warm
19    Kilifi          13.0          21.0                 cold
20       Voi          14.0          23.0                 warm
21     Narok          17.0          23.0                 warm
22   Bungoma          17.0          25.0                 warm
23    mukima          14.0          23.0                 warm

In [9]:
Total_towns = dt['Town'].count()
print(  f'The total numbers of towns {Total_towns}' )

The total numbers of towns 24

In [11]:
Average_min_temp = dt["Min_temp(°C)"].mean()
print(f'The average minimum temperature is {Average_min_temp}')

The average minimum temperature is 18.5

In [16]:
Average_max_temp =dt['Max_temp(°C)'].mean()
print(f"The Average maximum temperature is {Average_max_temp:.1f}")

The Average maximum temperature is 25.9

In [17]:
Total_min_temp = dt['Min_temp(°C)'].sum()
print(f'The total minimum temperature is {Total_min_temp}')

The total minimum temperature is 444.0

In [19]:
Max_min_temp = dt['Min_temp(°C)'].max()
print(f'The max minimum temperature is {Max_min_temp}')

The max minimum temperature is 27.0

In [25]:
High_temperature_rec = dt[dt['Max_temp(°C)'] >30]
print(High_temperature_rec)

       Town  Min_temp(°C)  Max_temp(°C) Temperature Category
8      Meru          23.0          33.0            very warm
10  Kericho          27.0          33.0            very warm
13  Malindi          25.0          34.0            very warm
16  Nanyuki          25.0          32.0            very warm

In [31]:
from IPython.display import display
with pd.option_context('display.max_rows', 6):
  display(dt[dt['Max_temp(°C)']>29])

        Town  Min_temp(°C)  Max_temp(°C) Temperature Category
8       Meru          23.0          33.0            very warm
9       Embu          25.0          30.0            very warm
10   Kericho          27.0          33.0            very warm
13   Malindi          25.0          34.0            very warm
15  Kakamega          20.0          30.0            very warm
16   Nanyuki          25.0          32.0            very warm

# Displaying the grouped and aggregated dataframe

In [40]:
# Grouping by 'Temperature Category' and calculate the mean of 'Min_temp(°C)' and 'Max_temp(°C)'
grouped_dt = dt.groupby('Temperature Category').agg({
    'Min_temp(°C)': 'mean',
    'Max_temp(°C)': 'mean'
}).round(2)

# Display the grouped and aggregated dataframe
print(grouped_dt)

                      Min_temp(°C)  Max_temp(°C)
Temperature Category
cold                         14.50         20.75
very warm                    23.86         31.57
warm                         16.85         24.46

In [41]:
# Sort by 'Min_temp(°C)' in ascending order
sorted_dt_min = dt.sort_values(by='Min_temp(°C)', ascending=True)
sorted_dt_min

        Town  Min_temp(°C)  Max_temp(°C) Temperature Category
19    Kilifi          13.0          21.0                 cold
0    Nairobi          14.0          22.0                 warm
20       Voi          14.0          23.0                 warm
18      Lamu          14.0          22.0                 warm
23    mukima          14.0          23.0                 warm
3     Nakuru          14.0          20.0                 cold
5      Thika          15.0          21.0                 cold
17    Isiolo          16.0          21.0                 cold
4    Eldoret          16.0          23.0                 warm
11  Naivasha          16.0          28.0                 warm
6      Nyeri          16.0          25.0                 warm
22   Bungoma          17.0          25.0                 warm
7   Machakos          17.0          25.0                 warm
21     Narok          17.0          23.0                 warm
15  Kakamega          20.0          30.0            very warm
2     Kisumu          20.0          26.0                 warm
14   Garissa          20.0          25.0                 warm
1    Mombasa          22.0          29.0            very warm
8       Meru          23.0          33.0            very warm
12    Kitale          24.0          28.0                 warm
13   Malindi          25.0          34.0            very warm
16   Nanyuki          25.0          32.0            very warm
9       Embu          25.0          30.0            very warm
10   Kericho          27.0          33.0            very warm

# MERGING DIFFERNT DATA FRAMES.

In [43]:
# Dataframe 1 (df1)
data1 = {
    'Town': ['Nairobi', 'Mombasa', 'Kisumu', 'Nakuru'],
    'Min_temp(°C)': [14.0, 22.0, 20.0, 14.0],
    'Max_temp(°C)': [22.0, 29.0, 26.0, 20.0]
}
df1 = pd.DataFrame(data1)

# Dataframe 2 (df2)
data2 = {
    'Town': ['Nairobi', 'Mombasa', 'Eldoret', 'Nyeri'],
    'Population': [4500000, 1200000, 290000, 300000],
    'Elevation(m)': [1795, 50, 2100, 1780]
}
df2 = pd.DataFrame(data2)

# Merging the dataframes on 'Town' column using an inner join
merged_df = pd.merge(df1, df2, on='Town', how='inner')

# Display the merged dataframe
print(merged_df)

      Town  Min_temp(°C)  Max_temp(°C)  Population  Elevation(m)
0  Nairobi          14.0          22.0     4500000          1795
1  Mombasa          22.0          29.0     1200000            50

In [44]:
merged_df = pd.merge(df1, df2, on='Town', how='left')